package model.client;

import java.util.Date;

import model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 27 13:06:24 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void createRow(String empEmail, String sal, Date from, Date to) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createRow",new String [] {"java.lang.String","java.lang.String","java.util.Date","java.util.Date"},new Object[] {empEmail, sal, from, to});
        return;
    }

    public void updateRowby_EFFDT_UPDATE_MODE(String empEmail, String sal,
                                              Date effectiveDate) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateRowby_EFFDT_UPDATE_MODE",new String [] {"java.lang.String","java.lang.String","java.util.Date"},new Object[] {empEmail, sal, effectiveDate});
        return;
    }

    public void updateRowby_EFFDT_UPDATE_CORRECTION(String empEmail,
                                                    String sal,
                                                    Date effectiveDate) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateRowby_EFFDT_UPDATE_CORRECTION",new String [] {"java.lang.String","java.lang.String","java.util.Date"},new Object[] {empEmail, sal, effectiveDate});
        return;
    }

    public void deleteRow(String empEmail, Date from, Date to) {
        Object _ret =
            this.riInvokeExportedMethod(this,"deleteRow",new String [] {"java.lang.String","java.util.Date","java.util.Date"},new Object[] {empEmail, from, to});
        return;
    }
}
